GET 127.0.0.1:9001/gateway/e-commerce-nacos-client/nacos-client/clients/e-commerce-nacos-client
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjIzLFwidXNlcm5hbWVcIjpcInJhaW55MVwifSIsImp0aSI6ImVjYmYwOTVlLWNjY2EtNDBjMC1iMWUzLTI0NThiNDJjYTQ4NSIsImV4cCI6MTY2NzIxMjM3NX0.EzAuNNFtyYim1ZvqrN1_PLY_KZi-19iKKpcRWUfJTUBwMmThKmwqNo07WHmCvvih9cDlndL8CvyeJl7pv4iYRddberiylaO_xmUVepFiYL1ROXHrilOx2i0rDKxlSn83boK_WiYuM-hbnY_jzcXOcx9xFNOR7Xe9PGL4IXjLsDMbBig-9DgSTmNemexqu48SzV6BoZr-MsD6EGvsp3BWrnlaNhCQAO0trWn416txHz4MkTLp8zB7GYvJ9vtdAR582GFxu8avCB2Djgd1k7nUeV8uKtMbSubeKRV2vYaEwSRma-lyLG7I1jBgUFQUrsdH06BZnOO5dgb-gz6QhkCfcw
token: e-commerce