server:
  port: 7001
  servlet:
    context-path: /e-commerce-authority

spring:
  application:
    name: e-commerce-authority
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848   # nacos服务地址,集群：server-addr: 127.0.0.1:8848,127.0.0.1:8858,127.0.0.1:8868
        namespace: 6d22a47f-36f9-44bd-93f0-e076b0707139
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.show_sql: true
      hibernate.format_sql: true
    open-in-view: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/e-commerce?authReconnect=true&useUnicode=true
    username: root
    password: 12345678
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 8
      idle-timeout: 30000
      connection-timeout: 45000
      auto-commit: true
      pool-name: ecommerce-hikariCP

# 暴露端点,以便commerce-admin服务可以详细展示当前服务的监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always



