server:
  port: 8000
  servlet:
    context-path: /e-commerce-nacos-client
spring:
  application:
    name: e-commerce-nacos-client  # 应用程序名称，也是构成Nacos配置管理中dataId字段的一部分
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848 # nacos服务地址,集群：server-addr: 127.0.0.1:8848,127.0.0.1:8858,127.0.0.1:8868
        namespace: 6d22a47f-36f9-44bd-93f0-e076b0707139   # nacos命名空间
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
      config:
        prefix: commerce
        file-extension: yaml
        enabled: true
        group: DEFAULT_GROUP
        namespace: 6d22a47f-36f9-44bd-93f0-e076b0707139
        server-addr: 127.0.0.1:8848

# 暴露端点,以便commerce-admin服务可以详细展示当前服务的监控信息
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
