server:
  port: 7001
  servlet:
    context-path: /commerce-admin
spring:
  application:
    name: commerce-admin
  security:
    user:
      name: rainy
      password: 12345678
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848 # nacos服务地址,集群：server-addr: 127.0.0.1:8848,127.0.0.1:8858,127.0.0.1:8868
        namespace: 6d22a47f-36f9-44bd-93f0-e076b0707139
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
          user:
            name: rainy
            password: 12345678
  thymeleaf:
    check-template-location: false
    check-template: false



# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 这里开放所有端点。默认只打开health和info两个端点。
  endpoint:
    health:
      show-details: always
